### PR TITLE
WebDav support

### LINKED ISSUE #74: Add support for hosting WebDAV via CLI
**Is your feature request related to a problem? Please describe.**

I'd like to share files with other peoples which is already possible via the new path feature (e.g. `loophole path .`). But this does not allow uploading files.

**Describe the solution you'd like**

It would be awesome to have a new mode that allows bi-directional data transfer which is also easy to integrate into most desktop systems. First thing that comes to mind is [WebDAV](https://en.wikipedia.org/wiki/WebDAV). We could have something like `loophole webdav .` to expose the current directory via the WebDAV protocol. This can then be even mounted on other machines in the Windows Explorer, macOS Finder, Linux Gnome Files or Linux KDE Konqueror.

**Describe alternatives you've considered**

Alternative standard APIs for bidirectional transfer are for example [Amazon S3](https://en.wikipedia.org/wiki/Amazon_S3) (via [min.io](https://min.io/)). But the integration into common Desktop systems is not that easy. And I don't know whether there are already server implementations for S3 for Golang. So I guess adding WebDAV should be easier.

Are there other http-based protocols? FTP, SMB, etc. don't work via loophole.

**Additional context**

### PR DESCRIPTION
**Pull request by Morishiri**
Fixes #74

### CODE REVIEW

**Review by denny241 — COMMENTED** [review]
The message displaying the link should be adjusted, changing https:// to davs://
Aside from that everything looks good I think.

**Comment by 0x7f** [comment]
> The message displaying the link should be adjusted, changing https:// to davs://
> Aside from that everything looks good I think.

The commonly used protocol for webdav ist actually `https`. So I would keep it that way. Also just tried on my Mac and Finder only wants to mount WebDAV dirs when using `https`. It does not know the `davs` protocol.

**Comment by denny241** [comment]
That is kind of troublesome actually. The only reason I suggested that change is that the default Ubuntu Filemanager in 20.04 (Nautilus I believe?) doesn't accept the link if there is an https:// in front and requires the davs:// to work :/

**Comment by Morishiri** [comment]
> That is kind of troublesome actually. The only reason I suggested that change is that the default Ubuntu Filemanager in 20.04 (Nautilus I believe?) doesn't accept the link if there is an https:// in front and requires the davs:// to work :/

We can then present both links ;/

**Comment by 0x7f** [comment]
Hm, indeed, some Linux tools seem to required the `dav` or `davs` protocol :/ (e.g. see https://wiki.archlinux.org/index.php/WebDAV). But none of the RFCs mentiones this protocol ([RFC-2518](https://tools.ietf.org/html/rfc2518) or [RFC-4918](https://tools.ietf.org/html/rfc4918)). Would also vote for printing https as the main url and adding an info for linux users that you might need to use the davs url.

**Pull request merged**
